spring.application.name=api-gateway

server.port=8084

# ==============================
# CATALOG SERVICE
# ==============================

spring.cloud.gateway.server.webmvc.routes[0].id=catalog-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://cake-catalog-service:8080
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/cakes/**

# ==============================
# ORDER SERVICE
# ==============================

spring.cloud.gateway.server.webmvc.routes[1].id=order-service
spring.cloud.gateway.server.webmvc.routes[1].uri=http://cake-order-service:8081
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/orders/**

# ==============================
# RATING SERVICE
# ==============================

spring.cloud.gateway.server.webmvc.routes[2].id=rating-service
spring.cloud.gateway.server.webmvc.routes[2].uri=http://cake-rating-service:8082
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/ratings/**

# ==============================
# NOTIFICATION SERVICE
# ==============================

spring.cloud.gateway.server.webmvc.routes[3].id=notification-service
spring.cloud.gateway.server.webmvc.routes[3].uri=http://cake-notification-service:8083
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/notifications/**

# ==============================
# ACTUATOR
# ==============================

management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.gateway.enabled=true