apiVersion: apps/v1
kind: Deployment
metadata:
  name: cake-rating-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cake-rating-service
  template:
    metadata:
      labels:
        app: cake-rating-service
    spec:
      containers:
        - name: cake-rating-service
          image: cake-rating-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: cake-rating-service
spec:
  selector:
    app: cake-rating-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP